name: tests

on:
  pull_request:
    paths:
      - "payments/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies and Run Tests
        working-directory: payments
        run: |
          npm install
          npm run test:ci
